### ISSUE TITLE
Error startup

### ISSUE THREAD

**Issue by MizukageMaTes** [J3fftw1/SlimeXpansion#11]
## Description (Required)

Error on Startup server

## Server Log / Error Report

[13:50:21] [Server thread/INFO]: [SlimeXpansion] Enabling SlimeXpansion vDEV - 11 (git 88bc3bdd)
[13:50:21] [Server thread/INFO]: [SlimeXpansion] There is no such item with name SIGN
[13:50:21] [Server thread/INFO]: [SlimeXpansion] There is no such item with name GOLD_HELMET
[13:50:21] [Server thread/ERROR]: Error occurred while enabling SlimeXpansion vDEV - 11 (git 88bc3bdd) (Is it up to date?)
java.lang.NoSuchMethodError: 'void me.john000708.slimexpansion.SlimeXpansion$1.registerChargeableBlock(int)'
        at me.john000708.slimexpansion.SlimeXpansion.registerItems(SlimeXpansion.java:153) ~[?:?]
        at me.john000708.slimexpansion.SlimeXpansion.onEnable(SlimeXpansion.java:85) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-143]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-143]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435) ~[patched_1.15.2.jar:git-Paper-143]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-143]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-143]
        at java.lang.Thread.run(Thread.java:834) [?:?]

## Environment (Required)

 - Minecraft Version: 1.15.2 - Paper git 143
 - Slimefun Version: Slimefun4 DEV470
 - CS-CoreLib Version: DEV83
 - SlimeExpansion Version: DEV11

**Comment by ClayCoffee** [comment]
The API has been updated.
So it can't work

**Comment by MizukageMaTes** [comment]
> The API has been updated.
> So it can't work

So every time you update the API it will give an error?

**Comment by J3fftw1** [comment]
> 
> 
> > The API has been updated.
> > So it can't work
> 
> So every time update the API it will give an error?

no only when the api changes

**Comment by MizukageMaTes** [comment]
> > > The API has been updated.
> > > So it can't work
> > 
> > 
> > So every time update the API it will give an error?
> 
> no only when the api changes

Understand. And can you correct the error in the last API in the paper?

**Comment by WalshyDev** [comment]
Fixed in [build 12](https://thebusybiscuit.github.io/builds/J3fftw1/SlimeXpansion/master/#12)
